cask "aerospork" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '1.1.2'
  sha256 "d420e190229f8581c411afc2f3bdb81c682d947b476a60e9df42cb736c237ddd"

  url "https://github.com/wbsmolen/aerospork/releases/download/v#{version}/aerospork-v#{version}.zip"
  name "AeroSpork"
  desc "AeroSpork is an i3-like tiling window manager for macOS"
  homepage "https://github.com/wbsmolen/aerospork"
  conflicts_with cask: 'aerospork-dev'

  depends_on macos: ">= :ventura" # macOS 13

  # No quarantine-stripping postflight. It used to run
  #   xattr -d com.apple.quarantine ...
  # which Homebrew rejects in submitted casks, and which did nothing for anyone downloading the
  # zip directly — it only worked because brew happened to run it locally. The real fix is
  # notarization (see build-release.sh), which makes Gatekeeper accept the app on any Mac.

  app "aerospork-v#{version}/AeroSpork.app"

  # The CLI is shipped INSIDE the app bundle, and this points at the installed copy rather than at
  # the zip's bin/ (which is only a symlink into the same place). A standalone copy on disk would be
  # a bare Mach-O, and a notarization ticket cannot be stapled to one of those -- Apple's own
  # `syspolicy_check distribution` calls that "Notary Ticket Missing ... Severity: Fatal". Inside
  # the bundle it is covered by the app's stapled ticket and works with no network.
  binary "#{appdir}/AeroSpork.app/Contents/MacOS/aerospork-cli", target: "aerospork"

  binary "aerospork-v#{version}/shell-completion/zsh/_aerospork",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospork"
  binary "aerospork-v#{version}/shell-completion/bash/aerospork",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospork"
  binary "aerospork-v#{version}/shell-completion/fish/aerospork.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospork.fish"

  manpage "aerospork-v#{version}/manpage/aerospork-balance-sizes.1"
  manpage "aerospork-v#{version}/manpage/aerospork-close-all-windows-but-current.1"
  manpage "aerospork-v#{version}/manpage/aerospork-close.1"
  manpage "aerospork-v#{version}/manpage/aerospork-config.1"
  manpage "aerospork-v#{version}/manpage/aerospork-debug-windows.1"
  manpage "aerospork-v#{version}/manpage/aerospork-enable.1"
  manpage "aerospork-v#{version}/manpage/aerospork-exec-and-forget.1"
  manpage "aerospork-v#{version}/manpage/aerospork-flatten-workspace-tree.1"
  manpage "aerospork-v#{version}/manpage/aerospork-focus-back-and-forth.1"
  manpage "aerospork-v#{version}/manpage/aerospork-focus-monitor.1"
  manpage "aerospork-v#{version}/manpage/aerospork-focus.1"
  manpage "aerospork-v#{version}/manpage/aerospork-fullscreen.1"
  manpage "aerospork-v#{version}/manpage/aerospork-join-with.1"
  manpage "aerospork-v#{version}/manpage/aerospork-layout.1"
  manpage "aerospork-v#{version}/manpage/aerospork-list-apps.1"
  manpage "aerospork-v#{version}/manpage/aerospork-list-exec-env-vars.1"
  manpage "aerospork-v#{version}/manpage/aerospork-list-modes.1"
  manpage "aerospork-v#{version}/manpage/aerospork-list-monitors.1"
  manpage "aerospork-v#{version}/manpage/aerospork-list-windows.1"
  manpage "aerospork-v#{version}/manpage/aerospork-list-workspaces.1"
  manpage "aerospork-v#{version}/manpage/aerospork-macos-native-fullscreen.1"
  manpage "aerospork-v#{version}/manpage/aerospork-macos-native-minimize.1"
  manpage "aerospork-v#{version}/manpage/aerospork-mode.1"
  manpage "aerospork-v#{version}/manpage/aerospork-move-mouse.1"
  manpage "aerospork-v#{version}/manpage/aerospork-move-node-to-monitor.1"
  manpage "aerospork-v#{version}/manpage/aerospork-move-node-to-workspace.1"
  manpage "aerospork-v#{version}/manpage/aerospork-move-workspace-to-monitor.1"
  manpage "aerospork-v#{version}/manpage/aerospork-move.1"
  manpage "aerospork-v#{version}/manpage/aerospork-open-settings.1"
  manpage "aerospork-v#{version}/manpage/aerospork-reload-config.1"
  manpage "aerospork-v#{version}/manpage/aerospork-resize.1"
  manpage "aerospork-v#{version}/manpage/aerospork-split.1"
  manpage "aerospork-v#{version}/manpage/aerospork-summon-workspace.1"
  manpage "aerospork-v#{version}/manpage/aerospork-trigger-binding.1"
  manpage "aerospork-v#{version}/manpage/aerospork-volume.1"
  manpage "aerospork-v#{version}/manpage/aerospork-workspace-back-and-forth.1"
  manpage "aerospork-v#{version}/manpage/aerospork-workspace.1"
  manpage "aerospork-v#{version}/manpage/aerospork.1"
end
